<link rel="stylesheet" type="text/css" href="<%=basePath%>js/lib/jqurey/jquery-ui.min.css"/>
<script src="<%=basePath%>js/lib/jqurey/jquery-ui.min.js"></script>

<link rel="stylesheet" type="text/css" href="<%=basePath%>js/lib/timepicker/jquery-ui-timepicker-addon.css"/>
<script src="<%=basePath%>js/lib/timepicker/jquery-ui-timepicker-addon.js"></script>
<script src="<%=basePath%>js/lib/timepicker/jquery-ui-sliderAccess.js"></script>
